### PR TITLE
acceptance test for successful check connection implemented and working

### PR DESCRIPTION
**Pull request by Ismail-Naziz**
## What
successful check connection in acceptance tests

This PR covers a successful check of connection with right credentials for JWT authentication

### CODE REVIEW

**Review by maxi297 — APPROVED** [review]
LGTM!

**Review by maxi297 — APPROVED** [review]
LGTM!

**Review by maxi297 — CHANGES_REQUESTED** [review]
Actually, doing a bit more testing caused me to get an error which I don't think the user would understand:
```
"('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>, <OpenSSLError(code=109052027, lib=13, reason=123, reason_text=header too long)>, <OpenSSLError(code=109052006, lib=13, reason=102, reason_text=bad object header)>, <OpenSSLError(code=109576458, lib=13, reason=524554, reason_text=nested asn1 error)>, <OpenSSLError(code=109576458, lib=13, reason=524554, reason_text=nested asn1 error)>])
Traceback (most recent call last):
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/main.py\", line 8, in <module>
    run()
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/source_snowflake/run.py\", line 13, in run
    launch(source, sys.argv[1:])
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/.venv/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 235, in launch
    for message in source_entrypoint.run(parsed_args):
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/.venv/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 117, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.discover(source_spec, config))
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/.venv/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 152, in discover
    catalog = self.source.discover(self.logger, config)
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 79, in discover
    streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/source_snowflake/source.py\", line 169, in streams
    authenticator = SnowflakeJwtAuthenticator.from_config(config)
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/source_snowflake/authenticator.py\", line 53, in from_config
    public_key_finger_print = cls.calculate_public_key_fingerprint(formatted_private_key, password,sub)
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/source_snowflake/authenticator.py\", line 99, in calculate_public_key_fingerprint
    private_key_object = load_pem_private_key(private_key.encode(),
  File \"/Users/maxime/devel/code/airbyte/airbyte-integrations/connectors/source-snowflake/.venv/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py\", line 494, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>, <OpenSSLError(code=109052027, lib=13, reason=123, reason_text=header too long)>, <OpenSSLError(code=109052006, lib=13, reason=102, reason_text=bad object header)>, <OpenSSLError(code=109576458, lib=13, reason=524554, reason_text=nested asn1 error)>, <OpenSSLError(code=109576458, lib=13, reason=524554, reason_text=nested asn1 error)>])"
```

I got this by screwing with the `credentials.private_key`. Can we get this to be a config error with a better error message? Else, our engineers will get pinged for input errors of the user. A system_error also happens if I enter an invalid database or schema while this should be a config one

**Comment by Ismail-Naziz** [comment]
This issue will be adressed in this PR https://github.com/artefactory/airbyte/pull/29 as it is dedicated to basic errors in check

**Comment by maxi297** [comment]
If the key is a valid key, https://github.com/artefactory/airbyte/pull/29 works fine but if the `-----BEGIN PRIVATE KEY-----` is not provided or another algorithm was used to generate the key, this will create a system error.

Also note that there are typos in [the documentation](https://github.com/artefactory/airbyte/blob/c5c30dfd71c068c5e31a9ddb3912bc14b973dea4/docs/integrations/sources/snowflake.md#L53-L61) (`the the` for example) and that the command for both cases is the same. Can we update that?

**Comment by Ismail-Naziz** [comment]
It is documented how you need to generate the key and the format that it should have. Also, it is reminded in the error message that PEM format is required. If you search for the definition of the PEM format, you will find that is necessary to have header and footer.
I have handled the issue to raise the error in case the footer and header are not present in the key.

**Comment by maxi297** [comment]
> I have handled the issue to raise the error in case the footer and header are not present in the key
Where?

**Comment by Ismail-Naziz** [comment]
In this [PR](https://github.com/artefactory/airbyte/pull/29) , you can see in this [commit],(https://github.com/artefactory/airbyte/pull/29/commits/8efa93355751f19a4c8863f858118bb60496f43f#diff-77674c8a0dc16412970c3dcbb9995dd053cadfc01ec96d1542fad28e0511d33f) in the method _format_private_key that if the key does not start or end with footer or header, we raise the error, it will be caught on the source to indicate to the user to use the PEM format.

**Review by bazarnov — APPROVED** [review]

**Pull request merged**
